
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class Tbexample
{
    private readonly System.Collections.Generic.Dictionary<int, example> _dataMap;
    private readonly System.Collections.Generic.List<example> _dataList;
    
    public Tbexample(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, example>(_buf.Count);
        _dataList = new System.Collections.Generic.List<example>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            example _v;
            _v = global::cfg.example.Deserializeexample(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, example> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<example> DataList => _dataList;

    public example GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public example Get(int key) => _dataMap[key];
    public example this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

